### ISSUE TITLE
Cannot invoke kind-level procedures when logged in with a real token

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#233]
Getting the following error:
```
papiea-engine    | CasbinAuthorizer checkPermission error TypeError: Cannot read property 'kind' of undefined
papiea-engine    |     at evaluateMember (/code/papiea-engine/node_modules/expression-eval/index.js:48:27)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:94:14)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:60:71)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:87:16)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:50)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:16)
papiea-engine    |     at Enforcer.enforce (/code/papiea-engine/node_modules/casbin/lib/coreEnforcer.js:279:32)
papiea-engine    |     at CasbinAuthorizer.checkPermission (/code/papiea-engine/src/auth/casbin.ts:32:32)
papiea-engine    |     at PerProviderAuthorizer.checkPermission (/code/papiea-engine/src/auth/authz.ts:156:27)
papiea-engine    |     at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Trying to look deeper into it, in here https://github.com/nutanix/papiea-js/blob/13ecded8e2a10337fcfafdf2532e1ee94f257c8c/papiea-engine/src/auth/casbin.ts#L26-L36

Printing `user`, `object` and `action` gives the following:
1. `user`:
```
papiea-engine    | SHLOMI:::: user
{  
   "tenant":"1c7fb69f-ed02-4e47-9881-79e8f0bf90ca",
   "tenant-email":"shlomi.vaknin@nutanix.com",
   "tenant-fname":"Shlomi",
   "tenant-lname":"Vaknin",
   "tenant-role":"account-admin",
   "owner":"shlomi.vaknin@nutanix.com",
   "authorization":"Bearer eyJhbGciOiJS...DrB-w",
   "provider_prefix":"xi_clusters",
   "provider_version":"0.0.1",
   "iat":1563399927,
   "exp":1564004727
}
```
2. `object`:
```
papiea-engine    | SHLOMI:::: object
{  
   "kind":{  
      "name":"imaged_cluster",
      "name_plural":"imaged_clusters",
      "kind_structure":{  
         "imaged_cluster":{  
            "type":"object",
            "title":"imaged_cluster",
            "description":"Stores an imaged cluster",
            "x-papiea-entity":"spec-only",
            "properties":{  
               "name":{  
                  "type":"string"
               },
               "number_of_hosts":{  
                  "type":"number"
               },
               "cvm_ip":{  
                  "x-papiea":"status-only",
                  "type":"string"
               },
               "host_reference_list":{  
                  "x-papiea":"status-only",
                  "type":"array",
                  "items":{  
                     "type":"object",
                     "required":[  
                        "uuid",
                        "kind"
                     ],
                     "properties":{  
                        "uuid":{  
                           "type":"string"
                        },
                        "name":{  
                           "type":"string"
                        },
                        "kind":{  
                           "type":"string"
                        }
                     }
                  }
               },
               "geolocation_reference":{  
                  "x-papiea":"status-only",
                  "type":"object",
                  "required":[  
                     "uuid",
                     "kind"
                  ],
                  "properties":{  
                     "uuid":{  
                        "type":"string"
                     },
                     "name":{  
                        "type":"string"
                     },
                     "kind":{  
                        "type":"string"
                     }
                  }
               },
               "cluster_status":{  
                  "x-papiea":"status-only",
                  "type":"string"
               }
            }
         }
      },
      "intentful_signatures":{  

      },
      "dependency_tree":{  

      },
      "kind_procedures":{  
         "create_aws_cluster":{  
            "name":"create_aws_cluster",
            "argument":{  
               "Create_AWS_Cluster_Input":{  
                  "type":"object",
                  "title":"Create AWS Cluster Input",
                  "description":"All info required to create a xi-clusters cluster on AWS bare metal hosts",
                  "properties":{  
                     "name":{  
                        "type":"string",
                        "title":"Name of the cluster",
                        "example":"New cluster"
                     },
                     "geolocation_reference":{  
                        "type":"object",
                        "title":"Geolocation reference",
                        "description":"Geolocation where xi-clusters should run in",
                        "required":[  
                           "uuid",
                           "kind"
                        ],
                        "properties":{  
                           "uuid":{  
                              "type":"string",
                              "example":"3fa85f64-5717-4562-b3fc-2c963f66afa6"
                           },
                           "kind":{  
                              "type":"string",
                              "example":"geolocation"
                           },
                           "name":{  
                              "type":"string",
                              "example":"entity_name"
                           }
                        }
                     },
                     "host_type_reference":{  
                        "type":"object",
                        "title":"Host type reference",
                        "description":"AWS instance type on which xi-clusters should run",
                        "required":[  
                           "uuid",
                           "kind"
                        ],
                        "properties":{  
                           "uuid":{  
                              "type":"string",
                              "example":"0ed241b6-d0a4-46fe-ab12-6f0b3ee0da7c"
                           },
                           "kind":{  
                              "type":"string",
                              "example":"host_type"
                           },
                           "name":{  
                              "type":"string",
                              "example":"entity_name"
                           }
                        }
                     },
                     "number_of_hosts":{  
                        "type":"number",
                        "title":"The requested number of hosts",
                        "example":3
                     },
                     "aos_version":{  
                        "type":"string",
                        "title":"AOS Version",
                        "example":"5.10.3.2"
                     },
                     "network":{  
                        "type":"object",
                        "title":"Cluster network configuration",
                        "properties":{  
                           "source_cidr":{  
                              "type":"string",
                              "title":"Allowed IPs cidr",
                              "description":"Only IPs belonging to this cidr will be allowed to connect to these hosts. This is essentially AWS security groups for the hosts",
                              "example":"0.0.0.0/0"
                           },
                           "use_default_subnet":{  
                              "type":"boolean",
                              "title":"Use the default VPC's default subnet",
                              "description":"Start the cluster in the region's default VPC default subnet, and assign a public ip to the cluster nodes",
                              "example":true
                           },
                           "autogenerate_uvms_private_subnet":{  
                              "type":"boolean",
                              "title":"Generate a private subnet for the UVMs",
                              "description":"If true, a new private subnet will be generated for the UVMs of this cluster. The private subnet will be routed through a NAT on the instance's public subnet to have Internet access",
                              "example":true
                           }
                        }
                     }
                  }
               }
            },
            "result":{  
               "Create_AWS_Cluster_Output":{  
                  "type":"object",
                  "title":"Create AWS Cluster Output",
                  "properties":{  
                     "cloud_formation_url":{  
                        "type":"string",
                        "title":"Cloudformation URL",
                        "description":"The URL to follow in order to start cluster creation in the user AES account"
                     },
                     "cluster_reference":{  
                        "type":"object",
                        "title":"Created Cluster reference",
                        "description":"The reference to the created imaged_cluster",
                        "required":[  
                           "uuid",
                           "kind"
                        ],
                        "properties":{  
                           "uuid":{  
                              "type":"string",
                              "example":"entity_uuid"
                           },
                           "kind":{  
                              "type":"string",
                              "example":"kind_name"
                           },
                           "name":{  
                              "type":"string",
                              "example":"entity_name"
                           }
                        }
                     }
                  }
               }
            },
            "execution_strategy":0,
            "procedure_callback":"http://docker.for.mac.localhost:9999/imaged_cluster/create_aws_cluster"
         }
      },
      "entity_procedures":{  
         "rename":{  
            "name":"rename",
            "argument":{  

            },
            "result":{  

            },
            "execution_strategy":0,
            "procedure_callback":"http://docker.for.mac.localhost:9999/imaged_cluster/rename"
         }
      }
   }
}
```
3. `action`:
```
papiea-engine    | SHLOMI:::: action "call_create_aws_cluster"
```
And true enough, the object does not have a `metadata.kind` in it (as described in the model).

Is this the intended object that is checked?

p.s. 
If I use an admin s2s key (either papiea or provider), this seems to work fine, probably this entire step is not executed.

**Comment by shlomi-nx** [comment]
Continuing to look I found:
https://github.com/nutanix/papiea-js/blob/13ecded8e2a10337fcfafdf2532e1ee94f257c8c/papiea-engine/src/entity/entity_api_impl.ts#L193-L199

So the object we are setting is indeed `{kind: kind}` which is not what the model expects. 

Changing this definition to `{metadata: { kind: kind.name} }` gets us to the next step, which is:
```
papiea-engine    | CasbinAuthorizer checkPermission error TypeError: Cannot read property 'tenant_uuid' of undefined
papiea-engine    |     at evaluateMember (/code/papiea-engine/node_modules/expression-eval/index.js:48:27)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:94:14)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:60:71)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:50)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:87:50)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:87:16)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:50)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:16)
papiea-engine    |     at evaluate (/code/papiea-engine/node_modules/expression-eval/index.js:89:16)
papiea-engine    |     at Enforcer.enforce (/code/papiea-engine/node_modules/casbin/lib/coreEnforcer.js:279:32)
```

So, it seems that the model needs to change for kind/provider level procedure, as there is no notion of an `owner` of a procedure, nor a `tenant`. Here is how I propose to approach this:
1. if you recall, at procedure definition, we can supply a map which defines RBAC. In this map we need to state the permissions this specific procedure will need to have. For example:
```javascript
imaged_cluster.kind_procedure('create_aws_cluster', 
  {"imaged_cluster":[Create, Read], 
    "imaged_hosts":[Create, Read]}, 
  proc_strategy, aws_cluster_struct, aws_cluster_output_struct, create_aws_cluster)
```

In this example, we define that this procedure needs to be able to create and read both imaged_clusters and imaged_hosts. 
2. So I think we can completely remove the `call_procedure` rights check, instead, an entity procedure will have an implicit `{'entity_kind':[Read]}` which has to be enforced, and other level procedures will need to manually specify the rights that the procedure needs to check against
3. When invoking a procedure, all the rights in this map needs to be checked and all must be allowed.

Does this makes sense?

**Comment by shlomi-nx** [comment]
Thinking further about this problem, it seems that the model needs to change for kind/provider level procedure, as there is no notion of an `owner` of a procedure, nor a `tenant`. 

Here is how I propose to approach this:
1. if you recall, at procedure definition, we can supply a map which defines RBAC. I now recall why we put it there. In this map we need to state the permissions this specific procedure will need to have. For example:
   ```javascript
   imaged_cluster.kind_procedure('create_aws_cluster', 
     {"imaged_cluster":[Create, Read], 
      "imaged_hosts":  [Create, Read]}, 
     proc_strategy, aws_cluster_struct, aws_cluster_output_struct, create_aws_cluster)
   ```

   In this example, we define that this procedure needs to be able to create and read both imaged_clusters and imaged_hosts. 
2. I think we can completely remove the `call_procedure` rights check, instead:
    1.  an entity level procedure will have an implicit `{'entity_kind':[Read]}` which has to be enforced (because it must read the entity to provide it as an argument)
     2. other level procedures will need to manually specify all the rights that they will need in order to work. 
    3. We can even restrict what the procedure is allowed to do if it did not request a particular right, even if the user has the right. So if a procedure did not ask for reading permissions of a particular kind, and inside it it tries to read it, an unauthorized exception needs to be raised on the SDK.
3. When invoking a procedure, all the rights in this map needs to be checked and all must be allowed.

Does this makes sense?

**Comment by adolgarev** [comment]
@shlomi-nx please take a look at https://github.com/nutanix/papiea-js/pull/212 regarding Call procedure auth

**Comment by shlomi-nx** [comment]
@adolgarev yes, I'm familiar with that one, but procedure auth logic needs to change for the reasons I opened this issue.

**Comment by adolgarev** [comment]
Propose to not do authz for procedure calls, lets keep authz for entities only, procedure may talk on behalf of the calling user and do with entities what he is allowed to do, the user itself may call nay procedure (entity, kind, provider). Procedure may also use any other s2s key.
@shlomi-nx also proposes to add API to check permissions thus user or procedure may check beforehand that they have all necessary rights and not fail in the middle due to this.

**Comment by shlomiv** [comment]
@adolgarev We can go ahead with what we discussed. 

Procedures are not authorized by themselves, rather we rely on their operations on the various entities to keep authorization intact. 
1. Lets remove current authorization for procedures
2. Lets add apis that allows to test if a particular user can do a particular action on a particular entity
   - These apis will only allow a user to test his own rights
   - This way a user could check if he has certain permissions without actually attempting to make any changes
   - A procedure handler could then simply invoke that api while impersonating as the requesting user to get the right answer

**Comment by shlomi-nx** [comment]
@Emulebest Here is the description we discussed during our call today

**Comment by shlomi-nx** [comment]
@Emulebest 
> 1. Lets remove current authorization for procedures
Lets have this as a first PR (First priority)

> 2. Lets add apis that allows to test if a particular user can do a particular action on a particular entity
>   
>   * These apis will only allow a user to test his own rights
>   * This way a user could check if he has certain permissions without actually attempting to make any changes
>   * A procedure handler could then simply invoke that api while impersonating as the requesting user to get the right answer

Lets have this in another PR (Third Priority)
